//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hmhyWebservice2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainUser
    {
        public int userId { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
    }
}
